# Generated by Django 4.2.11 on 2024-04-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['year', 'make', 'model'],
            },
        ),
    ]
