# Generated by Django 4.2.11 on 2024-04-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0010_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('electric', 'Electric'), ('gasoline', 'Gasoline')], default='gasoline', max_length=50),
        ),
    ]
