# Generated by Django 4.2.11 on 2024-04-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0011_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('electric', 'Electric'), ('diesel', 'Diesel')], default='gasoline', max_length=50),
        ),
    ]
