# Generated by Django 4.2.11 on 2024-04-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0035_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
