# Generated by Django 4.2.11 on 2024-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0040_alter_car_fuel_type_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='gasoline', max_length=50),
        ),
    ]
