# Generated by Django 4.2.11 on 2024-05-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0044_alter_car_fuel_type_alter_car_transmission'),
        ('car_catalog', '0045_alter_car_fuel_type_alter_car_transmission'),
    ]

    operations = [
    ]
